/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package view;

import java.awt.print.PrinterException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import repository.PhieuDen_Repository;
import viewModel.InPhieuDen;

/**
 *
 * @author FPT
 */
public class Inphieu extends javax.swing.JFrame {
    
       

    /** Creates new form Inphieu */
    public Inphieu(String mapd, String tenkh) {
        
         PhieuDen_Repository  phphieuden = new PhieuDen_Repository();
       
        initComponents();
        double ttp=0;
        List<InPhieuDen> list_inphieuden = phphieuden.getphieudenctbymapd(mapd);
            txt1.setText(txt1.getText() + "-----------------------------------------*-------------------------------------------------------------------------------\n");
        txt1.setText(txt1.getText() + "- Phiêú Dền -\n");
        txt1.setText(txt1.getText() + "- Thư Viện Sách Nh 6 -\n\n");
        txt1.setText(txt1.getText() + "- hotline : 0973394351\n\n");
        txt1.setText(txt1.getText() + "- Thời gian : ngày 18/4/2023 \n\n");
        txt1.setText(txt1.getText() + "_ Khách Hàng : "+tenkh+"  \n\n");
        txt1.setText(txt1.getText() + "-------------------------------------------------------------------------------------------------------------------------\n\n");
        txt1.setText(txt1.getText() + "   TênSach  " + "\tMã Sách " + "\tĐộ h hao " +"\t ngày Trả "+"\t Ly do " + "\n\n");
        for (InPhieuDen i : list_inphieuden) {
            
            txt1.setText(txt1.getText() + "   " + i.getTensach() + "\t" + i.getMasach() + "\t" + i.getDohuhao() +"\t" + i.getNgaytra()+"\t"+i.getLido()+ "\n\n");
            txt1.setText(txt1.getText() + "---------------------------------------------------------------------------------------------------------------------\n");
            ttp += i.getSotienphat();
        }
        
        txt1.setText(txt1.getText() + "------------------------------------------------------------------------------------------------------------------------\n");
        txt1.setText(txt1.getText() + "\tTổng Tiền : \t " + ttp + "\n");
        txt1.setText(txt1.getText() + "------------------------------------------------------------------------------------------------------------------------\n");
        txt1.setText(txt1.getText() + "                    Cảm Ơn Quý Khách\n");
        txt1.setText(txt1.getText() + "------------------------------------------------------------------------------------------------------------------------\n");
        txt1.setText(txt1.getText() + "------------------------------------------------------------------------------------------------------------------------\n");


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        btninphieu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        btninphieu.setText("In Phiếu");
        btninphieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninphieuActionPerformed(evt);
            }
        });

        jButton1.setText("Huỷ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btninphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninphieu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninphieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninphieuActionPerformed
        // TODO add your handling code here:
        try {
            txt1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Inphieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btninphieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninphieu;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables

}
