/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ChiTietSach;
import model.Sach;
import service.ChiTietSachSevice;
import service.SachSevice;
import service.impl.ChiTietSachSeviceImpl;
import service.impl.SachSeviceImpl;

/**
 *
 * @author ACER
 */
public class ViewChiTietSach extends javax.swing.JFrame {

    private ChiTietSachSevice chiTietSachSevice = new ChiTietSachSeviceImpl();
    private SachSevice sachSevice = new SachSeviceImpl();
    private List<ChiTietSach> listCT = new ArrayList<>();
    private String id;
    private String ma;
    private String anh;
    private String tensach;
    private String masach;

    /**
     * Creates new form ViewChiTietSach
     */
    public ViewChiTietSach(String idSach, String mas, String hinhAnh, String tenSach, String maSach) {
        initComponents();
        id = idSach;
        ma = mas;
        anh = hinhAnh;
        tensach = tenSach;
        masach = maSach;
        lbNameSach.setText(tenSach);
        loadDataToTable();
    }

    private void loadDataToTable() {
        listCT = chiTietSachSevice.getAll(id);

        DefaultTableModel dtm = (DefaultTableModel) this.tbListCTSach.getModel();
        dtm.setRowCount(0);
        for (ChiTietSach x : listCT) {
            Object[] rowData = {
                x.getMaQuyenSach(), x.getMaISBN(), x.isTinhTrang() ? "Còn Mới" : "Đã Cũ", x.getDoHuHao(), x.isTrangThai() ? "Đã Mượn" : "Chưa Được Mượn"
            };

            dtm.addRow(rowData);
        }
    }

    public void loadSP(int i) {
        listCT = chiTietSachSevice.getAll(id);
        ChiTietSach qlnv = listCT.get(i);
        lbNameSach.setText(tensach);
        lbMaQuyenSach.setText(qlnv.getMaQuyenSach());
        txtMaISBN.setText(qlnv.getMaISBN());
        txtDoHuHao.setText(String.valueOf(qlnv.getDoHuHao()));
        if (qlnv.isTrangThai()) {
            rdbDaMuon.setSelected(true);
        } else {
            rdbChuDuocMuon.setSelected(false);
        }
        if (qlnv.isTinhTrang()) {
            rdbConMoi.setSelected(true);
        } else {
            rdbCu.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaISBN = new javax.swing.JTextField();
        txtDoHuHao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListCTSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbNameSach = new javax.swing.JLabel();
        lbMaQuyenSach = new javax.swing.JLabel();
        rdbChuDuocMuon = new javax.swing.JRadioButton();
        rdbDaMuon = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdbConMoi = new javax.swing.JRadioButton();
        rdbCu = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThem.setBackground(new java.awt.Color(255, 255, 102));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(255, 255, 102));
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Quyển Sách");

        btnThoat.setBackground(new java.awt.Color(255, 255, 102));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel4.setText("Ma ISBN");

        jLabel5.setText("Độ Hư Hao");

        jLabel6.setText("Trạng Thái");

        jLabel1.setText("Tên Sách");

        tbListCTSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Quyển Sách", "Mã ISBN", "Tình Trạng", "Độ Hư Hao", "Trạng Thái"
            }
        ));
        tbListCTSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListCTSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListCTSach);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(java.awt.Color.lightGray);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Thông Tin Chi Tiết Sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        lbNameSach.setBackground(new java.awt.Color(255, 255, 255));
        lbNameSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbNameSach.setForeground(new java.awt.Color(255, 0, 51));
        lbNameSach.setText("Sách JJ");

        lbMaQuyenSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbMaQuyenSach.setForeground(new java.awt.Color(255, 0, 51));
        lbMaQuyenSach.setText("S0000.00");

        buttonGroup1.add(rdbChuDuocMuon);
        rdbChuDuocMuon.setSelected(true);
        rdbChuDuocMuon.setText("Chưa Được Mượn");

        buttonGroup1.add(rdbDaMuon);
        rdbDaMuon.setText("Đã Mượn");

        jLabel7.setText("Tình Trang");

        buttonGroup2.add(rdbConMoi);
        rdbConMoi.setSelected(true);
        rdbConMoi.setText("Còn Mới");

        buttonGroup2.add(rdbCu);
        rdbCu.setText("Cũ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtDoHuHao, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                                .addComponent(lbNameSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(lbMaQuyenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(79, 79, 79)
                                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbConMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)
                                                .addComponent(rdbCu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(rdbChuDuocMuon)
                                                .addGap(52, 52, 52)
                                                .addComponent(rdbDaMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(104, 104, 104))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMaISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNameSach))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(lbMaQuyenSach))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMaISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThoat)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(rdbConMoi)
                            .addComponent(rdbCu))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txtDoHuHao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdbChuDuocMuon)
                    .addComponent(rdbDaMuon))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tbListCTSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListCTSachMouseClicked
        int i = tbListCTSach.getSelectedRow();
        loadSP(i);
    }//GEN-LAST:event_tbListCTSachMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);
        String maISBN = txtMaISBN.getText();
        String doHuHao = "";

        boolean trangthai = true;
        if (rdbChuDuocMuon.isSelected()) {
            trangthai = false;
        } else if (rdbDaMuon.isSelected()) {
            trangthai = true;
        }
        boolean tinhtrang = false;
        if (rdbConMoi.isSelected()) {
            tinhtrang = true;
            doHuHao = "100";
        } else if (rdbCu.isSelected()) {
            tinhtrang = false;
            doHuHao = txtDoHuHao.getText();
        }
        ChiTietSach ctd = chiTietSachSevice.getOne(maISBN);
        if (maISBN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã ISBN của cuốn sách rồi thử lại");
        }else if(ctd != null){
            JOptionPane.showMessageDialog(this, "Mã ISBN đã tồn tại");
        }
        else if (doHuHao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập độ hư hao của cuốn sách");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                ChiTietSach cts = new ChiTietSach(id, maISBN, Float.valueOf(doHuHao), trangthai, tinhtrang);
                JOptionPane.showMessageDialog(this, this.chiTietSachSevice.add(cts, masach));
                loadDataToTable();
            }

        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);
        String maISBN = txtMaISBN.getText();
        String doHuHao = "";
        String maS = tbListCTSach.getValueAt(tbListCTSach.getSelectedRow(), 0).toString();
        boolean trangthai = true;
        if (rdbChuDuocMuon.isSelected()) {
            trangthai = false;
        } else if (rdbDaMuon.isSelected()) {
            trangthai = true;
        }
        boolean tinhtrang = false;
        if (rdbConMoi.isSelected()) {
            tinhtrang = true;
            doHuHao = "100";
        } else if (rdbCu.isSelected()) {
            tinhtrang = false;
            doHuHao = txtDoHuHao.getText();
        }
        if (maISBN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã ISBN của cuốn sách rồi thử lại");
        } else if (doHuHao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập độ hư hao của cuốn sách");
        } else if (Integer.parseInt(doHuHao) < 20) {
            JOptionPane.showMessageDialog(this, "Cuốn sách đã quá cũ không dùng được nữa");
        } else if (Integer.parseInt(doHuHao) > 100) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng độ hư hao");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                ChiTietSach cts = new ChiTietSach(id, maISBN, Float.valueOf(doHuHao), trangthai, tinhtrang);
                JOptionPane.showMessageDialog(this, this.chiTietSachSevice.update(cts, maS));
                loadDataToTable();
            }
        }

    }//GEN-LAST:event_btnCapNhatActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewChiTietSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewChiTietSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewChiTietSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewChiTietSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewChiTietSach().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMaQuyenSach;
    private javax.swing.JLabel lbNameSach;
    private javax.swing.JRadioButton rdbChuDuocMuon;
    private javax.swing.JRadioButton rdbConMoi;
    private javax.swing.JRadioButton rdbCu;
    private javax.swing.JRadioButton rdbDaMuon;
    private javax.swing.JTable tbListCTSach;
    private javax.swing.JTextField txtDoHuHao;
    private javax.swing.JTextField txtMaISBN;
    // End of variables declaration//GEN-END:variables
}
