/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NXB;
import model.TheLoai;
import service.NXBSevice;
import service.TheLoaiSevice;
import service.impl.NXBSeviceImpl;
import service.impl.TheLoaiSeviceImpl;

/**
 *
 * @author ACER
 */
public class ViewNXB extends javax.swing.JFrame {

    private NXBSevice nXBSevice;
    private TheLoaiSevice theLoaiSevice;
    private List<TheLoai> listtl = new ArrayList<>();
    private List<NXB> listnxb = new ArrayList<>();
    private String vadateEmail = "^[A-Za-z0-9]+[A-Za-z0-9]*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)$";
    private String vadateSDT = "^((09|03|07|08|05)+([0-9]{8}))$";

    public ViewNXB() {
        initComponents();

        nXBSevice = new NXBSeviceImpl();
        theLoaiSevice = new TheLoaiSeviceImpl();

        loadDataToTableNXB();
        loadDataToTableTL();
    }

    private void loadDataToTableNXB() {
        listnxb = nXBSevice.getAll();

        DefaultTableModel dtm = (DefaultTableModel) this.tbListNXB.getModel();
        dtm.setRowCount(0);
        for (NXB x : listnxb) {
            Object[] rowData = {
                x.getMaNXB(), x.getTenNXB(), x.getDiaChi(), x.getSdt(), x.getEmail(), x.getWebsite()
            };

            dtm.addRow(rowData);
        }
    }

    private void loadDataToTableTL() {
        listtl = theLoaiSevice.getAll();

        DefaultTableModel dtm = (DefaultTableModel) this.tbTheLoai.getModel();
        dtm.setRowCount(0);
        for (TheLoai x : listtl) {
            Object[] rowData = {
                x.getMaTL(), x.getTenTL()
            };

            dtm.addRow(rowData);
        }
    }

    public void loadTL(int i) {
        listtl = theLoaiSevice.getAll();
        TheLoai tl = listtl.get(i);
        lbMaTL.setText(tl.getMaTL());
        txtTenTL.setText(tl.getTenTL());
    }

    public void loadNXB(int i) {
        listnxb = nXBSevice.getAll();
        NXB nxb = listnxb.get(i);
        lbMaNXB.setText(nxb.getMaNXB());
        txtTenNXB.setText(nxb.getTenNXB());
        txtDiaChiNXB.setText(nxb.getDiaChi());
        txtSDTNXB.setText(nxb.getSdt());
        txtEmailNXB.setText(nxb.getEmail());
        txtWebSiteNXB.setText(nxb.getWebsite());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListNXB = new javax.swing.JTable();
        txtTenNXB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChiNXB = new javax.swing.JTextField();
        txtSDTNXB = new javax.swing.JTextField();
        txtEmailNXB = new javax.swing.JTextField();
        txtWebSiteNXB = new javax.swing.JTextField();
        btnThemNXB = new javax.swing.JButton();
        btnCapNhatNXB = new javax.swing.JButton();
        btnThoat1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lbMaNXB = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbTheLoai = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        lbMaTL = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenTL = new javax.swing.JTextField();
        btnThemTL = new javax.swing.JButton();
        btnCapNhatTL = new javax.swing.JButton();
        bntThoat2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(java.awt.Color.lightGray);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Thông Tin Chi Tiết NXB và Thể Loại");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jLabel1.setText("Tên NXB");

        tbListNXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NXB", "Tên NXB", "Địa Chỉ", "SĐT", "Email", "Website"
            }
        ));
        tbListNXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListNXBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListNXB);

        jLabel3.setText("Địa Chỉ");

        jLabel4.setText("SĐT");

        jLabel5.setText("Email");

        jLabel6.setText("Website");

        btnThemNXB.setBackground(new java.awt.Color(255, 255, 102));
        btnThemNXB.setText("Thêm");
        btnThemNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNXBActionPerformed(evt);
            }
        });

        btnCapNhatNXB.setBackground(new java.awt.Color(255, 255, 102));
        btnCapNhatNXB.setText("Cập Nhật");
        btnCapNhatNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatNXBActionPerformed(evt);
            }
        });

        btnThoat1.setBackground(new java.awt.Color(255, 255, 102));
        btnThoat1.setText("Thoát");
        btnThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoat1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Mã NXB");

        lbMaNXB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaNXB.setForeground(new java.awt.Color(255, 0, 51));
        lbMaNXB.setText("NXB001");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenNXB)
                            .addComponent(txtDiaChiNXB)
                            .addComponent(txtSDTNXB)
                            .addComponent(txtEmailNXB)
                            .addComponent(txtWebSiteNXB, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(79, 79, 79)
                        .addComponent(btnThemNXB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCapNhatNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThoat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbMaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbMaNXB))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemNXB)
                            .addComponent(btnCapNhatNXB))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDiaChiNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEmailNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnThoat1)
                                .addGap(5, 5, 5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSDTNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWebSiteNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("NXB", jPanel1);

        tbTheLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Thể Loại", "Tên Thể Loại"
            }
        ));
        tbTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTheLoaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbTheLoai);

        jLabel7.setText("Mã TL");

        lbMaTL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbMaTL.setForeground(new java.awt.Color(255, 0, 51));
        lbMaTL.setText("TL001");

        jLabel9.setText("Tên Thể Loại");

        btnThemTL.setBackground(new java.awt.Color(255, 255, 102));
        btnThemTL.setText("Thêm");
        btnThemTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTLActionPerformed(evt);
            }
        });

        btnCapNhatTL.setBackground(new java.awt.Color(255, 255, 102));
        btnCapNhatTL.setText("Cập Nhật");
        btnCapNhatTL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTLActionPerformed(evt);
            }
        });

        bntThoat2.setBackground(new java.awt.Color(255, 255, 102));
        bntThoat2.setText("Thoát");
        bntThoat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntThoat2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThemTL)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaTL, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCapNhatTL)
                        .addGap(110, 110, 110)
                        .addComponent(bntThoat2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lbMaTL))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemTL)
                    .addComponent(btnCapNhatTL)
                    .addComponent(bntThoat2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Thể Loại", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNXBActionPerformed
        String tenNXB = txtTenNXB.getText();
        String diaChi = txtDiaChiNXB.getText();
        String sdt = txtSDTNXB.getText();
        Boolean checkSDT = sdt.matches(vadateSDT);
        String email = txtEmailNXB.getText();
        Boolean checkMail = email.matches(vadateEmail);
        String web = txtWebSiteNXB.getText();
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);
        if (tenNXB.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhà xuất bản rồi thử lại!");
        } else if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ rồi thử lại!");
        } else if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại rồi thử lại!");
        } else if (checkSDT == false) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng!");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email rồi thử lại!");
        } else if (checkMail == false) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng!");
        } else if (web.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập website rồi thử lại!");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                NXB nxb = new NXB(null, null, tenNXB, diaChi, sdt, email, web);
                JOptionPane.showMessageDialog(this, nXBSevice.add(nxb));
                loadDataToTableNXB();
            }
        }
    }//GEN-LAST:event_btnThemNXBActionPerformed

    private void btnCapNhatNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatNXBActionPerformed
        String tenNXB = txtTenNXB.getText();
        String diaChi = txtDiaChiNXB.getText();
        String sdt = txtSDTNXB.getText();
        Boolean checkSDT = sdt.matches(vadateSDT);
        String email = txtEmailNXB.getText();
        Boolean checkMail = email.matches(vadateEmail);
        String web = txtWebSiteNXB.getText();
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);

        if (tenNXB.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhà xuất bản rồi thử lại!");
        } else if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ rồi thử lại!");
        } else if (sdt.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số điện thoại rồi thử lại!");
        } else if (checkSDT == false) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không đúng định dạng!");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email rồi thử lại!");
        } else if (checkMail == false) {
            JOptionPane.showMessageDialog(this, "Email không đúng định dạng!");
        } else if (web.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập website rồi thử lại!");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                String ma = tbListNXB.getValueAt(tbListNXB.getSelectedRow(), 0).toString();
                NXB nxb = new NXB(null, null, tenNXB, diaChi, sdt, email, web);
                JOptionPane.showMessageDialog(this, nXBSevice.update(nxb, ma));
                loadDataToTableNXB();
            }

        }
    }//GEN-LAST:event_btnCapNhatNXBActionPerformed

    private void btnThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoat1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnThoat1ActionPerformed

    private void tbListNXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListNXBMouseClicked
        int i = tbListNXB.getSelectedRow();
        loadNXB(i);
    }//GEN-LAST:event_tbListNXBMouseClicked

    private void btnThemTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTLActionPerformed
        String tenTL = txtTenTL.getText();
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn thêm không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);

        if (tenTL.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên thể loại rồi thử lại!");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                TheLoai tl = new TheLoai(null, null, tenTL);
                JOptionPane.showMessageDialog(this, theLoaiSevice.add(tl));
                loadDataToTableTL();
            }

        }
    }//GEN-LAST:event_btnThemTLActionPerformed

    private void btnCapNhatTLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTLActionPerformed
        String tenTL = txtTenTL.getText();
        int choose = JOptionPane.showConfirmDialog(this, "Bạn có muốn sửa không", "Choose", JOptionPane.YES_NO_CANCEL_OPTION);
        if (tenTL.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên thể loại rồi thử lại!");
        } else {
            if (choose == JOptionPane.YES_OPTION) {
                String ma = tbTheLoai.getValueAt(tbTheLoai.getSelectedRow(), 0).toString();
                TheLoai tl = new TheLoai(null, null, tenTL);
                JOptionPane.showMessageDialog(this, theLoaiSevice.update(tl, ma));
                loadDataToTableTL();
            }

        }
    }//GEN-LAST:event_btnCapNhatTLActionPerformed

    private void bntThoat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntThoat2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_bntThoat2ActionPerformed

    private void tbTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTheLoaiMouseClicked
        int i = tbTheLoai.getSelectedRow();
        loadTL(i);
    }//GEN-LAST:event_tbTheLoaiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNXB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNXB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntThoat2;
    private javax.swing.JButton btnCapNhatNXB;
    private javax.swing.JButton btnCapNhatTL;
    private javax.swing.JButton btnThemNXB;
    private javax.swing.JButton btnThemTL;
    private javax.swing.JButton btnThoat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbMaNXB;
    private javax.swing.JLabel lbMaTL;
    private javax.swing.JTable tbListNXB;
    private javax.swing.JTable tbTheLoai;
    private javax.swing.JTextField txtDiaChiNXB;
    private javax.swing.JTextField txtEmailNXB;
    private javax.swing.JTextField txtSDTNXB;
    private javax.swing.JTextField txtTenNXB;
    private javax.swing.JTextField txtTenTL;
    private javax.swing.JTextField txtWebSiteNXB;
    // End of variables declaration//GEN-END:variables
}
